name: Update hashes in Nix flake
on:
  push:
    branches-ignore:
      - main
    paths:
      - yarn.lock
      - package.json

permissions:
  contents: write

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Update hashes
        run: |
          yarn-berry-fetcher missing-hashes $DEVENV_ROOT/yarn.lock > $DEVENV_ROOT/missing-hashes.json
          yarn-berry-fetcher prefetch $DEVENV_ROOT/yarn.lock $DEVENV_ROOT/missing-hashes.json > $DEVENV_ROOT/yarn-hash.txt

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          push: true
          message: 'chore: update hashes in nix flake (automated)'
