# .github/workflows/build.yml
name: Build Artifacts

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cd.yaml'
      - 'flake.nix'  
      - 'flake.lock'  
      - 'package.json'
      - 'yarn.lock'
      - 'src/**/*'  
      - 'src-tauri/**/*'  

jobs:
  nix-build:
    name: Build (Linux & macOS)
    runs-on: ${{ matrix.platform.on }}
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - on: ubuntu-latest 
            name: linux-x86_64
          - on: ubuntu-24.04-arm 
            name: linux-aarch64
          - on: macos-latest 
            name: macos-aarch64
          - on: macos-13
            name: macos-x86_64
        avx:
          - true
          - false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-25.05

    - name: Set up Cachix cache (optional)
      uses: cachix/cachix-action@v15
      with:
        name: devenv

    - name: Build with Nix flake (with AVX)
      if: ${{ matrix.avx }}
      run: |
        nix build .#quikscore -L 2>&1
    - name: Build with Nix flake (without AVX)
      if: ${{ !matrix.avx }}
      run: |
        nix build .#quikscore-compat -L 2>&1

    - name: Upload Nix build artifacts (Linux)
      if: ${{ contains(matrix.platform.name, 'linux') }}
      uses: actions/upload-artifact@v4
      with:
        name: quikscore-${{ matrix.platform.name }}${{ matrix.avx && '-avx' || '' }}
        path: |
          result
    - name: Upload Nix build artifacts (macOS)
      if: ${{ contains(matrix.platform.name, 'macos') }}
      uses: actions/upload-artifact@v4
      with:
        name: quikscore-${{ matrix.platform.name }}${{ matrix.avx && '-avx' || '' }}
        path: |
          result/Applications

  windows-build:
    name: Build (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        avx:
          - true
          - false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'

    - name: Set up Yarn
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with: 
        toolchain: nightly-2025-06-08

    - name: Install OpenCV & Other dependencies (sccache, cmake, llvm)
      run: | 
        choco install opencv sccache cmake -y
        choco install llvm --version=19.1.7 --force

    - name: Set up Environment variables
      run: |
        echo "RUSTFLAGS=-Z threads=8" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "OPENCV_INCLUDE_PATHS=C:\tools\opencv\build\include" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "OPENCV_LINK_LIBS=+opencv_world4110" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "OPENCV_LINK_PATHS=+C:\tools\opencv\build\x64\vc16\lib" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Include OpenCV dll in Tauri config
      run: |
        cp C:\tools\opencv\build\x64\vc16\bin\opencv_world4110.dll src-tauri\opencv_world4110.dll

        $jsonPath = "src-tauri/tauri.conf.json"
        $json = Get-Content $jsonPath -Raw | ConvertFrom-Json

        # Add item to the list
        $json.bundle.resources += "opencv_world4110.dll"

        # Write the modified object back to the file as JSON
        $json | ConvertTo-Json -Depth 10 | Set-Content $jsonPath

    - name: Build Tauri app (with AVX)
      if: ${{ matrix.avx }}
      run: |
        yarn tauri build --features avx512
    - name: Build Tauri app (without AVX)
      if: ${{ !matrix.avx }}
      run: |
        yarn tauri build

    - name: Group Binary Bundle
      run: |
        mkdir -p src-tauri/target/release/bin
        mv src-tauri/target/release/opencv_world4110.dll src-tauri/target/release/bin/opencv_world4110.dll
        mv src-tauri/target/release/quikscore.exe src-tauri/target/release/bin/quikscore.exe

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: quikscore-windows-x86_64${{ matrix.avx && '-avx' || '' }}
        path: |
          src-tauri/target/release/bin
          src-tauri/target/release/bundle
