name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'src-tauri/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'src-tauri/**/*'

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Check code
        run: devenv tasks run quikscore:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Lint code
        run: devenv tasks run quikscore:lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Run Tests
        run: devenv tasks run quikscore:test
