name: Test Coverage
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yaml'
      - 'src-tauri/src/**/*'

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  test_coverage:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Generate coverage report
        run: devenv tasks run quikscore:coverage

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
