name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'src-tauri/**/*'

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash

      - name: Generate coverage report
        run: devenv tasks run quikscore:coverage

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
