name: 📅 Track Issue Start/End Dates 
on:
  issues:
    types: [assigned, closed]

jobs:
  update-dates:
    runs-on: ubuntu-latest
    env:
      PROJECT_NUMBER: 4  # <-- set your actual project number
      PROJECT_OWNER: ${{ github.repository_owner }}

    steps:
      - name: Determine field name and date
        id: vars
        run: |
          echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Update status to "In Progress"
        if: github.event.action == "assigned"
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/$PROJECT_OWNER/projects/$PROJECT_NUMBER
          github-token: ${{ secrets.UPDATE_PROJECT_V2_PAT }}
          field-name: "Status"
          field-value: "In Progress"

      - name: Set start date 
        if: github.event.action == "assigned"
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/$PROJECT_OWNER/projects/$PROJECT_NUMBER
          github-token: ${{ secrets.UPDATE_PROJECT_V2_PAT }}
          field-name: "Start Date"
          field-value: "${{ steps.vars.outputs.date }}"


      - name: Set end date 
        if: github.event.action == "closed"
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/$PROJECT_OWNER/projects/$PROJECT_NUMBER
          github-token: ${{ secrets.UPDATE_PROJECT_V2_PAT }}
          field-name: "End Date"
          field-value: "${{ steps.vars.outputs.date }}"
