name: 📅 Track Issue Start/End Dates

on:
  issues:
    types: [assigned, closed]

permissions:
  issues: write
  repository-projects: write

jobs:
  update-dates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          if ! command -v gh &>/dev/null; then
            curl -sSL https://github.com/cli/cli/releases/latest/download/gh_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz \
              | tar xz -C /usr/local
          fi

      - name: Update Start/End Date field in project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          event="${{ github.event.action }}"
          date=$(date -u +'%Y-%m-%d')
          field=$([ "$event" = "assigned" ] && echo "Start Date" || echo "End Date")

          # Replace with your actual project number
          PROJECT_NUM=4

          # Get project and field IDs via GraphQL
          projectId=$(gh api graphql -f query="query {
            repository(owner: \"${{ github.repository_owner }}\", name: \"${{ github.event.repository.name }}\") {
              projectV2(number: $PROJECT_NUM) { id }
            }
          }" -q .data.repository.projectV2.id)

          fieldId=$(gh api graphql -f query="query {
            repository(owner: \"${{ github.repository_owner }}\", name: \"${{ github.event.repository.name }}\") {
              projectV2(number: $PROJECT_NUM) {
                field(name: \"$field\") { id }
              }
            }
          }" -q .data.repository.projectV2.field.id)

          # Update the date field for this issue
          itemId=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} -q .id)
          gh api graphql -f query="mutation(\$input: UpdateProjectV2ItemFieldInput!) {
            updateProjectV2ItemField(input: \$input) { projectV2Item { id } }
          }" -f input="{
            \"projectId\": \"$projectId\",
            \"itemId\": \"$itemId\",
            \"fieldId\": \"$fieldId\",
            \"value\": {\"date\": \"$date\"}
          }"
